### ISSUE TITLE
ValueError: need more than 2 values to unpack

### ISSUE THREAD

**Issue by mhoelter** [SublimeText/AFileIcon#43]
#### Expected Behavior

Thanks so much for creating AFileIcon. It's a great package, and always one of the first I install with a new Sublime. However, I'm having an issue where the icons should appear, but aren't. 

#### Current Behavior

Icons aren't appearing:

<img width="232" alt="Screen Shot 2021-02-26 at 10 53 47 PM" src="https://user-images.githubusercontent.com/1654178/109375891-f4531080-7885-11eb-86de-b9d67f8dd0ac.png">

#### Possible Solution

Appears to be an issue with an included Python script (see console output below).

#### Steps to Reproduce (for bugs)

1. Open Sublime 3
2. No icons
3. Console error outputs

#### Your Environment

Running macOS Catalina 10.15.7
Sublime 3 Version 3.2.2 Build 3211
Python version 3.8.6

**Console Output:**
`A File Icon: Initializing settings
A File Icon: Initializing icons
         >>> All the necessary icons are provided
A File Icon: Getting installed themes
Traceback (most recent call last):
  File "/Users/Matthew/Library/Application Support/Sublime Text 3/Installed Packages/A File Icon.sublime-package/plugin.py", line 24, in plugin_loaded_async
  File "/Users/Matthew/Library/Application Support/Sublime Text 3/Installed Packages/A File Icon.sublime-package/core/settings.py", line 26, in add_listener
  File "/Users/Matthew/Library/Application Support/Sublime Text 3/Installed Packages/A File Icon.sublime-package/core/themes.py", line 15, in patch
  File "/Users/Matthew/Library/Application Support/Sublime Text 3/Installed Packages/A File Icon.sublime-package/core/themes.py", line 88, in _installed_themes
ValueError: need more than 2 values to unpack`

**Comment by deathaxe** [comment]
It looks like ST's API doesn't even return the names of the Default.sublime-theme or Adaptive.sublime-theme. Maybe a race condition with API not being ready within ST's async thread quick enough after startup.

Does it happen right after setting up ST with only A File Icon being present or do several other plugins exist already?

I am a bit curious, because once icons and themes are set up after installation those should be available even though something goes wrong upon application startup.

You not seeing icons indicates the `zzz A File Icon zzz` helper package not to be present and/or filled with valid files (icons and theme patches).
