### ISSUE TITLE
File icons not showing

### ISSUE THREAD

**Issue by kidager** [SublimeText/AFileIcon#6]
#### Expected Behavior
Next to each filename there should be an icon:
![image](https://user-images.githubusercontent.com/3314980/50901738-5851bb00-1419-11e9-9b28-07e5adca84ef.png)

#### Current Behavior
A blank space is shown next to files
![image](https://user-images.githubusercontent.com/3314980/50901779-791a1080-1419-11e9-8789-5305c7350dc5.png)

#### Possible Solution
\-

#### Steps to Reproduce (for bugs)
\-

#### Context
Nothing special, no updates (at least not manually), no project changes, no new plugins, it just appeared out of nowhere!

#### Your Environment
Sublime Text 3.1.1 Build 3176

`lsb_release -d`
`Description:    CentOS Linux release 7.6.1810 (Core)`

`uname -a`
`Linux centos 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

`Package Settings → A File Icon → Environment`
`No output`

`View → Show Console` with `"dev_mode": true`
```
A File Icon: Getting the current theme
         >>> DA.sublime-theme
A File Icon: Getting installed themes
         >>> {'DA UI': ['DA.sublime-theme'], 'Theme - Default': ['Adaptive.sublime-theme', 'Default.sublime-theme'], 'Theme - Glacier': ['Glacier.sublime-theme'], 'Theme - Darkmatter': ['Darkmatter.sublime-theme'], 'Enki Theme': ['Enki-Theme-Light.sublime-theme', 'Enki-Theme.sublime-theme'], 'Material Theme': ['Material-Theme-Darker.sublime-theme', 'Material-Theme-Lighter.sublime-theme', 'Material-Theme-Palenight.sublime-theme', 'Material-Theme.sublime-theme']}
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 1007, in run_
    return self.run()
  File "/home/jchaieb/.config/sublime-text-3/Installed Packages/A File Icon.sublime-package/common/utils/environment.py", line 34, in run
  File "/home/jchaieb/.config/sublime-text-3/Installed Packages/A File Icon.sublime-package/common/utils/environment.py", line 12, in _get_package_version
  File "/opt/sublime_text/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
SublimeLinter: sublime_linter.py:252  Delay linting '<untitled 85>' for 0.0s
SublimeLinter: linter.py:891          json: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: linter.py:891          annotations: checking lint mode 'background' vs lint reason 'on_load'
SublimeLinter: #15 linter.py:908      json: linting '<untitled 85>'
SublimeLinter: #16 linter.py:908      annotations: linting '<untitled 85>'
SublimeLinter: #15 linter.py:987      json: output:
  No JSON object could be decoded
SublimeLinter: #15 linter.py:1023     json: No match for line: 'No JSON object could be decoded'
SublimeLinter: #16 linter.py:981      annotations: no output
SublimeLinter: sublime_linter.py:449  Linting '<untitled 85>' took 0.10s
```

**Comment by deathaxe** [comment]
Thanks for the detailed debugging info. The issue should be fixed with v3.3.1. Please run Package Control's _Upgrade/Overwrite All_ command to force another update.

**Comment by shadowkrusha** [comment]
Updating fixed the issue for me 👍

**Comment by aziz-gh** [comment]
v
